version: "3.7"
services:
  reddit-clone-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: reddit-clone-db
    environment:
      - MYSQL_ROOT_PASSWORD=${REDDB_USER}
      - MYSQL_DATABASE=reddit_clone
    ports:
      - 3306:3306

  backend:
    image: reddit-clone-backend:dev
    build: .
    container_name: reddit-clone-backend
    restart: on-failure
    depends_on:
      - reddit-clone-db
    ports:
      - 8080:8080
    environment:
      - REDDB_URL=${REDDB_URL}
      - REDDB_USER=${REDDB_USER}
      - REDDB_PASS=${REDDB_PASS}
      - KEYSTORE_PRIVATE_KEY=${KEYSTORE_PRIVATE_KEY}

